f1_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "md:f1"                          # MotherDuck cloud DB
      schema: main
      threads: 1
      motherduck_token: "{{ env_var('MOTHERDUCK_TOKEN') }}"
